"""initial schema

Revision ID: 1280fb69f423
Revises: 
Create Date: 2026-06-27 04:42:25.832365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1280fb69f423'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('default_context', sa.String(), nullable=False),
    sa.Column('include_in_clustering', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('contexts',
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('context_id', 'user_id')
    )
    op.create_table('ranked_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=False),
    sa.Column('venue_location', sa.JSON(), nullable=True),
    sa.Column('venue_cuisines', sa.JSON(), nullable=False),
    sa.Column('venue_dietary_tags', sa.JSON(), nullable=False),
    sa.Column('venue_price_tier', sa.Integer(), nullable=True),
    sa.Column('venue_health_score', sa.Float(), nullable=True),
    sa.Column('venue_source', sa.String(), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occasion_tag', sa.String(), nullable=False),
    sa.Column('is_classic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['context_id', 'user_id'], ['contexts.context_id', 'contexts.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranked_items')
    op.drop_table('contexts')
    op.drop_table('users')
    # ### end Alembic commands ###
