"""initial schema

Revision ID: 33e373d0aabc
Revises: 
Create Date: 2026-06-27 04:28:07.404839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e373d0aabc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('cuisines', sa.JSON(), nullable=False),
    sa.Column('dietary_tags', sa.JSON(), nullable=False),
    sa.Column('price_tier', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ranked_items', sa.Column('user_id', sa.String(), nullable=False))
    op.drop_constraint(None, 'ranked_items', type_='foreignkey')
    op.create_foreign_key(None, 'ranked_items', 'contexts', ['context_id', 'user_id'], ['context_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ranked_items', type_='foreignkey')
    op.create_foreign_key(None, 'ranked_items', 'contexts', ['context_id'], ['context_id'])
    op.drop_column('ranked_items', 'user_id')
    op.drop_table('venues')
    # ### end Alembic commands ###
