"""Add_ranked_item_mvp_fields

Revision ID: 79b3af01e70a
Revises: 6bc3b7f9efa3
Create Date: 2026-06-27 10:34:41.206788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b3af01e70a'
down_revision: Union[str, Sequence[str], None] = '6bc3b7f9efa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranked_items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('ranked_items', sa.Column('personal_rating', sa.Integer(), nullable=True))
    op.add_column('ranked_items', sa.Column('reaction', sa.String(), nullable=True))
    op.add_column('ranked_items', sa.Column('meal_type', sa.String(), nullable=True))
    op.add_column('ranked_items', sa.Column('dishes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranked_items', 'dishes')
    op.drop_column('ranked_items', 'meal_type')
    op.drop_column('ranked_items', 'reaction')
    op.drop_column('ranked_items', 'personal_rating')
    op.drop_column('ranked_items', 'status')
    # ### end Alembic commands ###
